### ISSUE TITLE
Compiling SDL notes

### ISSUE THREAD

**Issue by nickrout** [agillis/esphome-configs#1]
Hi Andrew. Just trying your SDL samples on my ubuntu (actually mint) laptop and wanted to make some notes while I remember them, and maye for your benefit in documentation. (1 & 3 are dos matters, 2 looks like an error, although I know you are probably refactoring)

1. need to install pilllow and cairosvg from pip in the venv that is running esphome
2. needed to add 'modules' to line 37 of sdl-lvgl_elegant_clock.yaml so it reads    `files: [modules/common/color.yaml]`
3. needed to add keys for encryption_key, latitude and longitiude in secrets.yaml

I think that's all.

**Comment by agillis** [comment]
Great. Thanks.

1. This is covered in the install documentation on the ESPHome site
2. Changed.
3. This sort of thing is required for any ESPhome install. But I'll add a comment that this is required.

Let me know how it goes and if you come up with any other cool clock faces!

**Comment by nickrout** [comment]
Thanks, I missed the cairosvg myself, to may be an idea to add it just for emphasis. Entirely up to you of course. The compile message from missing cairosvg is quite different to the compile error for pillow. pillow gives an easy to implement pip install line in the errors. cairosvg missing gives a difficult to decipher error.

The clock is cool, and down to the second with my smart watch. Fun to watch them tick in unison. I like my smart watch face so much I may try to emulate it, but I am no artist!

**Comment by agillis** [comment]
Do you have a picture of the smart watch?

**Comment by nickrout** [comment]
Sorry for the delay, I was trying to find a pic online, and here we have a pic at last. Its called Trace of Time and is a Oneplus Watch 2 face.
![1000000423](https://github.com/user-attachments/assets/fd20ec23-5cc4-4410-be14-be54d8e99c5a)

**Comment by nickrout** [comment]
I have been trying to make a black clock face, but there are some oddities

![image](https://github.com/user-attachments/assets/d64ad05a-8e48-44ca-a81c-d9e0e3c2b186)

You  may notice that the marks at 12, 24, 36 and 48 minutes do not look right (are a little short) and the 0 minute doesn't quite line up.The changes from yours are very minimal, basically changing white to black.

```shell
diff sdl-lvgl_elegant_clock.yaml sdl-lvgl_elegant_clock-nick.yaml 
202c202,203
<                   bg_color: White
---
>                   bg_color: Black
>                   border_width: 0                  
210c211
<                         color: Black
---
>                         color: White
221c222
<                             color: Black
---
>                             color: White
232c233
<                         color: Black                       
---
>                         color: White                       
243c244
<                             color: Black
---
>                             color: White
```
Needless to say, yours looks fine. Any tips?

**Comment by Squelch** [comment]
> 1. This is covered in the install documentation on the ESPHome site

I could only find one mention for the needed cairosvg package in the ESPHome  docs as a note which is a little obscure. Attempting to compile without the module causes a crash with the following traceback which might be a little overwhelming for novice  users, albeit being clearly noted as the last call.

```
Traceback (most recent call last):
  File "/home/squelch/Repositories/venv/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 503, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 212, in write_cpp
    generate_cpp_contents(config)
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 224, in generate_cpp_contents
    CORE.flush_tasks()
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/core/__init__.py", line 684, in flush_tasks
    self.event_loop.flush_tasks()
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/home/squelch/Repositories/venv/lib/python3.12/site-packages/esphome/__main__.py", line 204, in wrapped
    await coro(conf)
  File "/home/squelch/Repositories/config/esphome/.esphome/external_components/ac85b617/esphome/components/image/__init__.py", line 288, in to_code
    image = load_svg_image(file_contents, resize)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/squelch/Repositories/config/esphome/.esphome/external_components/ac85b617/esphome/components/image/__init__.py", line 244, in load_svg_image
    from cairosvg import svg2png
ModuleNotFoundError: No module named 'cairosvg'
```

Perhaps an extra mention here could be useful as one might look for the missing module in the modules folder? This was my first reaction on first encounter tbh

FYI for future seekers:

Within the virtual python environment (venv)
`pip install esphome cairosvg`

**Comment by agillis** [comment]
The cairosvg package is required whenever you use svg files. Not sure why it's not set to auto load. But this error is telling you that you need it. I added it to my docs.
