### ISSUE TITLE
can not build guition-esp32-s3-4848s040-display_basic

### ISSUE THREAD

**Issue by lecrams** [agillis/esphome-configs#3]
Hi,

I want to port your guition-esp32-s3-4848s040-display_basic project for a waveshare esp32-s3-lcd-7

Trying to rebuild your guition-esp32-s3-4848s040-display_basic.yaml from the command line gives me the following error.

Any idea what I am doing wrong?

 esphome compile .\guition-esp32-s3-4848s040-display_basic.yaml
INFO ESPHome 2024.10.2
INFO Reading configuration .\guition-esp32-s3-4848s040-display_basic.yaml...
WARNING GPIO45 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Europe/Berlin'
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\Scripts\esphome.exe\__main__.py", line 7, in <module>
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\__main__.py", line 1018, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\__main__.py", line 996, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 1091, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 945, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 935, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 859, in validate_config
    result.run_validation_steps()
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 142, in run_validation_steps
    task.step.run(self)
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config.py", line 562, in run
    validated = schema(self.conf)
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\voluptuous_schema.py", line 35, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 281, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 251, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 379, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 855, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\voluptuous_schema.py", line 35, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 281, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 625, in validate_dict
    return base_validate(path, data.items(), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\voluptuous_schema.py", line 149, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 251, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 379, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 855, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\components\font\__init__.py", line 300, in _file_schema
    return validate_file_shorthand(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\components\font\__init__.py", line 265, in validate_file_shorthand
    return FILE_SCHEMA(
           ^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 254, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 377, in _exec
    v = func(v)
        ^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 281, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 855, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\components\font\__init__.py", line 301, in _file_schema
    return TYPED_FILE_SCHEMA(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\config_validation.py", line 1622, in validator
    value = Schema(schemas[key_v])(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\voluptuous_schema.py", line 35, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 281, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 251, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\validators.py", line 379, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\voluptuous\schema_builder.py", line 855, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\components\font\__init__.py", line 213, in download_web_font
    external_files.download_content(url, path)
  File "C:\Users\a5128563\AppData\Roaming\Python\Python312\site-packages\esphome\external_files.py", line 106, in download_content
    path.write_bytes(data)
  File "C:\Program Files\Python312\Lib\pathlib.py", line 1036, in write_bytes
    with self.open(mode='wb') as f:
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '.esphome\\font\\4568d52a\\font.ttf'

**Comment by agillis** [comment]
I'll take a look. In the mean time use guition-esp32-s3-4848s040-display_modular.yaml

**Comment by lecrams** [comment]
using guition-esp32-s3-4848s040-display_modular.yaml gives me the same error

**Comment by agillis** [comment]
I built both here and it works fine. I have had many issues myself getting ESPHome to build on Windows. It's probably an issue with your Windows python install. Try build a more simple yaml and see if that works. 

I recommend using Linux to build your YAML files.

**Comment by lecrams** [comment]
are you using the LVGL from the latest ESPhome version (2024.10.2).
When I build it from linux I get this error?

INFO ESPHome 2024.10.2
INFO Reading configuration ./sunton-esp32-8048s070-display_basic.yaml...
INFO Detected timezone 'Europe/Amsterdam'
Failed config

lvgl: [source ./sunton-esp32-8048s070-display_basic.yaml:148]
  displays:

    string value cannot be dictionary or list.
    - display_id: my_display
  touchscreens:
    - touchscreen_id: my_touchscreen

**Comment by agillis** [comment]
that file was made for some very old LVGL code so it's no longer valid. Try

sunton-esp32-8048s070-display_modular.yaml

**Comment by agillis** [comment]
All files should be building OK now.

**Comment by lecrams** [comment]
thx for the update. One I have ported this for a  waveshare esp32-s3-lcd-7, I will share it here

**Comment by agillis** [comment]
Great! I just purchased on of those. I'll add it to the supported devices.
